#用户 ----------------------------------------------------------
#登录
user-auth:
    path: /api/v1/user/auth
    controller: App\Controller\UserController::Auth
    methods: POST
#查看个人信息
user-info:
    path: /api/v1/user
    controller: App\Controller\UserController::info
    methods: GET
#修改个人信息
user-info-change:
    path: /api/v1/user
    controller: App\Controller\UserController::updateInfo
    methods: PUT
#查看他人信息
user-info-others:
    path: /api/v1/user/{id}
    controller: App\Controller\UserController::othersInfo
    methods: GET
#关注 ----------------------------------------------------------
#查看关注/粉丝列表
follow-list:
    path: /api/v1/follow/
    controller: App\Controller\FollowController::list
    methods: GET
#查看关注/粉丝数量
follow-list:
    path: /api/v1/follow/number
    controller: App\Controller\FollowController::number
    methods: GET
#查看他人关注/粉丝数量
follow-list-others:
    path: /api/v1/follow/number/{id}
    controller: App\Controller\FollowController::othersNumber
    methods: GET
#论坛 ----------------------------------------------------------
#版块列表
column-list:
    path: /api/v1/column/
    controller: App\Controller\ColumnController::list
    methods: GET
#版块信息
column-info:
    path: /api/v1/column/{id}
    controller: App\Controller\ColumnController::info
    methods: GET
#版块申请
column-apply:
    path: /api/v1/column/
    controller: App\Controller\ColumnController::apply
    methods: POST
#编辑版块信息
column-info-update:
    path: /api/v1/column/
    controller: App\Controller\ColumnController::updateInfo
    methods: PUT
#关注版块
column-follow:
    path: /api/v1/column/follow
    controller: App\Controller\ColumnController::follow
    methods: POST
#关注版块列表
column-follow-list:
    path: /api/v1/column/follow
    controller: App\Controller\ColumnController::followList
    methods: GET
#帖子列表
page-list:
    path: /api/v1/page/
    controller: App\Controller\PageController::list
    methods: GET
#发布帖子
page-publish:
    path: /api/v1/page/
    controller: App\Controller\PageController::publish
    methods: POST
#点赞帖子
page-like:
    path: /api/v1/page/{id}/like/
    controller: App\Controller\PageLikeController::like
    methods: POST
#取消点赞帖子
page-unlike:
    path: /api/v1/page/{id}/like/
    controller: App\Controller\PageLikeController::unlike
    methods: DELETE
#评论帖子
page-comment:
    path: /api/v1/page/{id}/comment/
    controller: App\Controller\PageCommentController::publish
    methods: POST
#点赞评论
page-comment-like:
    path: /api/v1/comment/{id}
    controller: App\Controller\CommentLikeController::like
    methods: POST
#取消点赞评论
page-comment-unlike:
    path: /api/v1/comment/{id}
    controller: App\Controller\CommentLikeController::unlike
    methods: DELETE
#收藏帖子列表
page-collect-list:
    path: /api/v1/page/{id}/collect/
    controller: App\Controller\PageCollectController::list
    methods: GET
#收藏帖子
page-collect:
    path: /api/v1/page/{id}/collect/
    controller: App\Controller\PageCollectController::collect
    methods: POST
#取消收藏帖子
page-collect:
    path: /api/v1/page/{id}/collect/
    controller: App\Controller\PageCollectController::uncollect
    methods: DELETE
#举报（帖子/评论）
page-report:
    path: /api/v1/page/{id}/report/
    controller: App\Controller\PageReportController::report
    methods: POST
#消息 ----------------------------------------------------------
#获取消息列表
message-list:
    path: /api/v1/message/
    controller: App\Controller\MessageController::list
    methods: GET
#发消息
message-send:
    path: /api/v1/message/
    controller: App\Controller\MessageController::send
    methods: POST
#功能 ----------------------------------------------------------
#获取功能菜单
menu:
    path: /api/v1/menu/
    controller: App\Controller\MenuController::index
    methods: GET
#更新菜单排列/显示
menu-update:
    path: /api/v1/menu/
    controller: App\Controller\MenuController::updateMenu
    methods: PUT
#查成绩
score:
    path: /api/v1/score/
    controller: App\Controller\ScoreController::index
    methods: GET
#查课表
lesson:
    path: /api/v1/lesson/
    controller: App\Controller\LessonController::index
    methods: GET
#查考试
exam:
    path: /api/v1/exam/
    controller: App\Controller\ExamController::index
    methods: GET
#四六级
cet:
    path: /api/v1/cet/
    controller: App\Controller\CetController::index
    methods: GET
