<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.xZogQI9' shared service.

return $this->privates['.service_locator.xZogQI9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'followUserService' => ['privates', 'App\\Service\\FollowUserService', 'getFollowUserServiceService.php', true],
    'userService' => ['privates', 'App\\Service\\UserService', 'getUserServiceService.php', true],
]);
