<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\FollowUserController::list' => ['privates', '.service_locator.iRRtux8', 'get_ServiceLocator_IRRtux8Service.php', true],
    'App\\Controller\\SchoolController::getNeeds' => ['privates', '.service_locator.BCMThel', 'get_ServiceLocator_BCMThelService.php', true],
    'App\\Controller\\SchoolController::list' => ['privates', '.service_locator.BCMThel', 'get_ServiceLocator_BCMThelService.php', true],
    'App\\Controller\\UserController::auth' => ['privates', '.service_locator.BGJ9ZQe', 'get_ServiceLocator_BGJ9ZQeService.php', true],
    'App\\Controller\\UserController::info' => ['privates', '.service_locator.xZogQI9', 'get_ServiceLocator_XZogQI9Service.php', true],
    'App\\Controller\\UserController::othersInfo' => ['privates', '.service_locator.xZogQI9', 'get_ServiceLocator_XZogQI9Service.php', true],
    'App\\Controller\\UserController::updateInfo' => ['privates', '.service_locator.XZ3pA2Y', 'get_ServiceLocator_XZ3pA2YService.php', true],
    'App\\Controller\\FollowUserController:list' => ['privates', '.service_locator.iRRtux8', 'get_ServiceLocator_IRRtux8Service.php', true],
    'App\\Controller\\SchoolController:getNeeds' => ['privates', '.service_locator.BCMThel', 'get_ServiceLocator_BCMThelService.php', true],
    'App\\Controller\\SchoolController:list' => ['privates', '.service_locator.BCMThel', 'get_ServiceLocator_BCMThelService.php', true],
    'App\\Controller\\UserController:auth' => ['privates', '.service_locator.BGJ9ZQe', 'get_ServiceLocator_BGJ9ZQeService.php', true],
    'App\\Controller\\UserController:info' => ['privates', '.service_locator.xZogQI9', 'get_ServiceLocator_XZogQI9Service.php', true],
    'App\\Controller\\UserController:othersInfo' => ['privates', '.service_locator.xZogQI9', 'get_ServiceLocator_XZogQI9Service.php', true],
    'App\\Controller\\UserController:updateInfo' => ['privates', '.service_locator.XZ3pA2Y', 'get_ServiceLocator_XZ3pA2YService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
