<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Service\School\SchoolNotExistService' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/School/SchoolDefaultInterface.php';
include_once $this->targetDirs[3].'/src/Service/School/SchoolNotExistService.php';

return $this->services['App\Service\School\SchoolNotExistService'] = new \App\Service\School\SchoolNotExistService(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
