<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK9b9Vxx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK9b9Vxx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerK9b9Vxx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerK9b9Vxx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerK9b9Vxx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'K9b9Vxx',
    'container.build_id' => '82c86620',
    'container.build_time' => 1554266352,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK9b9Vxx');
